FROM microsoft/aspnetcore-build

WORKDIR /app

COPY . .

RUN dotnet restore

RUN dotnet test ./NorthWind.Domain.UnitTest/NorthWind.Domain.UnitTest.csproj

RUN dotnet publish --output /out/ --configuration Release